#!/bin/bash

execpath=$(dirname $0)
srcpath=$PWD
igsuffix=$(echo $srcpath | sed 's/\//-/g')
[[ ! -d $execpath/.ignores ]] && mkdir -p $execpath/.ignores
ignorefile=$execpath/.ignores/ignore$igsuffix

if [[ ! -r $ignorefile ]]; then
    # Just useful in big C project
    findobjs=$(find . -maxdepth 2 -name "*.o")
    if [[ -n $findobjs ]]; then
        python3 $execpath/ignore_generator $PWD > $ignorefile
    fi
fi
