#!/bin/bash

execpath=$(dirname $0)
ignorefile=$execpath/ignore

findobjs=$(find . -maxdepth 2 -name "*.o")
if [[ -n $findobjs ]]; then
    python3 $execpath/ignore_generator $PWD > $ignorefile
else
    touch $ignorefile
fi
