#!/bin/bash

execpath=$(dirname $0)
srcpath=$PWD
igsuffix=$(echo $srcpath | sed 's/\//-/g')
[[ ! -d $execpath/.ignores ]] && mkdir -p $execpath/.ignores
ignorefile=$execpath/.ignores/ignore$igsuffix

if [[ $1 == "-i" ]]; then
    if [[ ! -r $ignorefile ]]; then
        # Just useful in big C project
        findobjs=$(find . -maxdepth 2 -name "*.o")
        if [[ -n $findobjs ]]; then
            python $execpath/ignore_generator $PWD > $ignorefile
        fi
    fi
elif [[ $1 == '-a' ]]; then
    shift
    echo "$@" >> $ignorefile
elif [[ $1 == '-d' ]]; then
    shift
    sed -i "\|"$@"|d" $ignorefile
fi
